In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv ('train.csv')
print (df)

        ID Province_State        Date  Confirmed  Deaths  Recovered    Active  \
0        0        Alabama  04-12-2020       3563      93        NaN    3470.0
1        1         Alaska  04-12-2020        272       8       66.0     264.0
2        2        Arizona  04-12-2020       3542     115        NaN    3427.0
3        3       Arkansas  04-12-2020       1280      27      367.0    1253.0
4        4     California  04-12-2020      22795     640        NaN   22155.0
...    ...            ...         ...        ...     ...        ...       ...
7095  7095       Virginia  08-31-2020     120575    2580    15085.0  102910.0
7096  7096     Washington  08-31-2020      74635    1915        NaN   72720.0
7097  7097  West Virginia  08-31-2020      10249     215     8017.0    2017.0
7098  7098      Wisconsin  08-31-2020      75603    1122    67234.0    7247.0
7099  7099        Wyoming  08-31-2020       3850      37     3181.0     632.0

      Incident_Rate  People_Tested  People_Hospitalized  Mortality_Rate  \
0         75.988020        21583.0                437.0        2.610160
1         45.504049         8038.0                 31.0        2.941176
2         48.662422        42109.0                  NaN        3.246753
3         49.439423        19722.0                130.0        2.109375
4         58.137726       190328.0               5234.0        2.812020
...             ...            ...                  ...             ...
7095    1412.626461      1586551.0                  NaN        2.139747
7096     980.118828      1461354.0                  NaN        2.565820
7097     571.883891       436047.0                  NaN        2.097766
7098    1298.477578      1253422.0                  NaN        1.484068
7099     665.216437        76273.0                  NaN        0.961039

      Testing_Rate  Hospitalization_Rate
0       460.300152             12.264945
1      1344.711576             11.397059
2       578.522286                   NaN
3       761.753354             10.156250
4       485.423869             22.961176
...            ...                   ...
7095  18587.633628                   NaN
7096  19190.735838                   NaN
7097  24330.984010                   NaN
7098  21527.457417                   NaN
7099  13178.715147                   NaN

[7100 rows x 13 columns]

In [3]:
stateList = ['Alabama','Alaska','Arizona','Arkansas','California','Colorado',
             'Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho',
             'Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana',
             'Maine','Maryland','Massachusetts','Michigan','Minnesota',
             'Mississippi','Missouri','Montana','Nebraska','Nevada',
             'New Hampshire','New Jersey','New Mexico','New York',
             'North Carolina','North Dakota','Ohio','Oklahoma','Oregon',
             'Pennsylvania','Rhode Island','South Carolina','South Dakota',
             'Tennessee','Texas','Utah','Vermont','Virginia','Washington',
             'West Virginia','Wisconsin','Wyoming']

In [5]:
for state in stateList:
    df_mask=df['Province_State']==state
    cur_state=df[df_mask]
    cur_state['death_diff'] = (cur_state['Deaths'] - cur_state['Deaths'].shift(1))
    cur_state['confirmed_diff'] = (cur_state['Confirmed'] - cur_state['Confirmed'].shift(1))
    file_name = "state_diff/{}.csv".format(state).replace(' ', '_')
    cur_state.to_csv(file_name, index=False)

/Users/mac/miniconda3/envs/hw2/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/mac/miniconda3/envs/hw2/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [6]:
wyo = pd.read_csv ('state_diff/Wyoming.csv')
wyo

,ID,Province_State,Date,Confirmed,Deaths,Recovered,Active,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,Testing_Rate,Hospitalization_Rate,death_diff,confirmed_diff
0,49,Wyoming,04-12-2020,270,0,137.0,270.0,54.299735,5459.0,40.0,0.000000,1097.860188,14.814815,NaN,NaN
1,99,Wyoming,04-13-2020,275,1,138.0,274.0,55.305285,5964.0,41.0,0.363636,1199.420803,14.909091,1.0,5.0
2,149,Wyoming,04-14-2020,282,1,140.0,281.0,56.713056,5964.0,43.0,0.354610,1199.420803,15.248227,0.0,7.0
3,199,Wyoming,04-15-2020,287,1,129.0,286.0,57.718607,6329.0,43.0,0.348432,1272.826000,14.982578,0.0,5.0
4,249,Wyoming,04-16-2020,296,2,148.0,294.0,59.528598,6427.0,43.0,0.675676,1292.534792,14.527027,1.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,6899,Wyoming,08-27-2020,3733,37,3060.0,636.0,645.000769,74532.0,215.0,0.991160,12877.899091,5.759443,0.0,53.0
138,6949,Wyoming,08-28-2020,3803,37,3086.0,680.0,657.095613,75236.0,NaN,0.972916,12999.538668,NaN,0.0,70.0
139,6999,Wyoming,08-29-2020,3795,37,3116.0,642.0,655.713345,75257.0,NaN,0.974967,13003.167121,NaN,0.0,-8.0
140,7049,Wyoming,08-30-2020,3829,37,3136.0,656.0,661.587984,75293.0,NaN,0.966310,13009.387327,NaN,0.0,34.0
141,7099,Wyoming,08-31-2020,3850,37,3181.0,632.0,665.216437,76273.0,NaN,0.961039,13178.715147,NaN,0.0,21.0